title: the "hello world" project
author: ian jarvis
email: lostinthegroove@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  # The "hello world" project is a project for developing and documenting 
  # an introduction to the foundations of digital media and 
  # digital media programming such as to provide resources for the incredible range of topics that I wish I had when I was starting my journey over 20 years ago.
# theme: minima
header_pages: ['']
plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:   
    twitter: L_ab_o # DO NOT include the @ character, or else the build will fail!
    github_username:  audiobeing # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage